### ISSUE TITLE
selected meshes not changing anymore

### ISSUE THREAD

**Issue by Masono03** [satetsu888/vts-chameleon#1] opened 2022-02-22 03:11 UTC
**Describe the bug**
if i select just a few meshes but not all they dont seem to change anymore after the recent vtube studio update.

**To Reproduce**
1. update vtube studio
2. open chameleon
3. try to change colors of formerly set mesh groups

**Expected behavior**
it changing like before the update 

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 21H2
 
**Additional context**
started happening after update so there mustve been a change

**Comment by satetsu888** [comment] 2022-02-22 13:35
Thank you for reporting the issue.
However, I could not reproduce it in my environment, with Windows, VTube Studio 1.17.0 and vts-chameleon 0.0.8 works fine.

If you are able to choose the color but that does not affect, vts-chameleon may have a connection error, please restart both VTube Studio and vts-chameleon and try again.

**Comment by Masono03** [comment] 2022-02-23 03:05
so i tried again i downloaded chameleon again and tried setting meshes but on newest vtube studio beta it does not select meshes anymore :/

**Comment by Masono03** [comment] 2022-02-23 03:09
if i select all at once it changes the complete models color but if i try to change individual meshes it doesnt even regognize them at all

**Comment by Masono03** [comment] 2022-02-23 03:14
oh so i tried around and aprently the meshes on my model got numbered diffrently after beta update so i have to just redo all selections and have clones of old mesh numbers that are broken so i guess its a per model issue

**Comment by satetsu888** [comment] 2022-02-23 14:05
Oh, I see. thank you so much for your work to find out root issue.
I think I need to make it easier to understand which ArtMesh is targeting by plugin.

Thanks again, closing this issue.

**Closed as completed by satetsu888** 2022-02-23 14:05 UTC
